# Generated by Django 3.1 on 2020-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyName', models.TextField(null=True)),
                ('Location', models.TextField(null=True)),
                ('Website', models.TextField(null=True)),
                ('ContractStartedOn', models.DateField(null=True)),
                ('ContractValidTill', models.DateField(null=True)),
                ('KCName', models.TextField(null=True)),
                ('KCEmail', models.EmailField(max_length=254, null=True)),
                ('KCPhone', models.IntegerField(null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyID', models.IntegerField(null=True)),
                ('StageID', models.IntegerField(null=True, unique=True)),
                ('StageName', models.TextField(null=True)),
                ('StageType', models.CharField(choices=[('SELECT', 'Select'), ('REJECT', 'Reject')], max_length=6, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
