# Generated by Django 3.1 on 2020-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyID', models.IntegerField(null=True)),
                ('StageID', models.IntegerField(null=True, unique=True)),
                ('StageName', models.TextField(null=True)),
                ('StageType', models.CharField(choices=[('SELECT', 'Select'), ('REJECT', 'Reject')], max_length=6, null=True)),
            ],
        ),
    ]
