# Generated by Django 3.1 on 2020-08-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JDCode', models.TextField(unique=True)),
                ('VacancyCode', models.TextField(null=True)),
                ('Title', models.TextField(null=True)),
                ('Location', models.TextField(null=True)),
                ('HiringManager', models.TextField(null=True)),
                ('RequisitionManager', models.TextField(blank=True)),
                ('KeySkills', models.TextField(null=True)),
                ('Role', models.TextField(blank=True)),
                ('DesiredExperience', models.TextField(blank=True)),
                ('Education', models.TextField(null=True)),
                ('MinExpRange', models.IntegerField(null=True)),
                ('MaxExpRange', models.IntegerField(null=True)),
                ('CTC', models.IntegerField(blank=True)),
                ('NoticePeriod', models.IntegerField(blank=True)),
                ('Status', models.TextField(max_length=1)),
                ('Openings', models.IntegerField(null=True)),
                ('No_Filled', models.IntegerField(null=True)),
                ('HiringMgrContact', models.IntegerField(null=True)),
                ('HiringMgrEmail', models.TextField(null=True)),
                ('AssignedDate', models.DateField(null=True)),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='records.client')),
                ('RecruiterAssignedTo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
        ),
    ]
