# Generated by Django 3.1 on 2020-09-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_staging_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staging',
            old_name='Int_P1_Date',
            new_name='Int_p1_Date',
        ),
        migrations.RenameField(
            model_name='staging',
            old_name='Int_P1_Result',
            new_name='Int_p1_Result',
        ),
    ]
