# Generated by Django 3.1 on 2020-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200915_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='contact_details_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='contact_details_phone2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='position',
            field=models.TextField(null=True),
        ),
    ]
