# Generated by Django 3.1 on 2020-08-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.TextField(null=True)),
                ('UserType', models.TextField(null=True)),
                ('UserDescription', models.TextField(null=True)),
                ('UserCompany', models.TextField(null=True)),
                ('UserStatus', models.TextField(max_length=1, null=True)),
                ('Password', models.TextField(null=True)),
                ('CreatedOn', models.DateField(auto_now_add=True, null=True)),
                ('Role', models.TextField(null=True)),
                ('Designation', models.TextField(null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('EmailID', models.EmailField(max_length=254, null=True)),
                ('Department', models.TextField(blank=True)),
                ('ValidTill', models.DateField(null=True)),
                ('UserReportsTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
        ),
    ]
